import 'package:flutter/material.dart';

final statesList = [
  DropdownMenuItem(child: Text("Alabama"), value: "AL"),
  DropdownMenuItem(child: Text("Alaska"), value: "AK"),
  DropdownMenuItem(child: Text("Arizona"), value: "AZ"),
  DropdownMenuItem(child: Text("Arkansas"), value: "AR"),
  DropdownMenuItem(child: Text("California"), value: "CA"),
  DropdownMenuItem(child: Text("Colorado"), value: "CO"),
  DropdownMenuItem(child: Text("Connecticut"), value: "CT"),
  DropdownMenuItem(child: Text("Delaware"), value: "DE"),
  DropdownMenuItem(child: Text("Florida"), value: "FL"),
  DropdownMenuItem(child: Text("Georgia"), value: "GA"),
  DropdownMenuItem(child: Text("Hawaii"), value: "HI"),
  DropdownMenuItem(child: Text("Idaho"), value: "ID"),
  DropdownMenuItem(child: Text("Illinois"), value: "IL"),
  DropdownMenuItem(child: Text("Indiana"), value: "IN"),
  DropdownMenuItem(child: Text("Iowa"), value: "IA"),
  DropdownMenuItem(child: Text("Kansas"), value: "KS"),
  DropdownMenuItem(child: Text("Kentucky"), value: "KY"),
  DropdownMenuItem(child: Text("Louisiana"), value: "LA"),
  DropdownMenuItem(child: Text("Maine"), value: "ME"),
  DropdownMenuItem(child: Text("Maryland"), value: "MD"),
  DropdownMenuItem(child: Text("Massachusetts"), value: "MA"),
  DropdownMenuItem(child: Text("Michigan"), value: "MI"),
  DropdownMenuItem(child: Text("Minnesota"), value: "MN"),
  DropdownMenuItem(child: Text("Mississippi"), value: "MS"),
  DropdownMenuItem(child: Text("Missouri"), value: "MO"),
  DropdownMenuItem(child: Text("Montana"), value: "MT"),
  DropdownMenuItem(child: Text("Nebraska"), value: "NE"),
  DropdownMenuItem(child: Text("Nevada"), value: "NV"),
  DropdownMenuItem(child: Text("New Hampshire"), value: "NH"),
  DropdownMenuItem(child: Text("New Jersey"), value: "NJ"),
  DropdownMenuItem(child: Text("New Mexico"), value: "NM"),
  DropdownMenuItem(child: Text("New York"), value: "NY"),
  DropdownMenuItem(child: Text("North Carolina"), value: "NC"),
  DropdownMenuItem(child: Text("North Dakota"), value: "ND"),
  DropdownMenuItem(child: Text("Ohio"), value: "OH"),
  DropdownMenuItem(child: Text("Oklahoma"), value: "OK"),
  DropdownMenuItem(child: Text("Oregon"), value: "OR"),
  DropdownMenuItem(child: Text("Pennsylvania"), value: "PA"),
  DropdownMenuItem(child: Text("Rhode Island"), value: "RI"),
  DropdownMenuItem(child: Text("South Carolina"), value: "SC"),
  DropdownMenuItem(child: Text("South Dakota"), value: "CD"),
  DropdownMenuItem(child: Text("Tennessee"), value: "TN"),
  DropdownMenuItem(child: Text("Texas"), value: "TX"),
  DropdownMenuItem(child: Text("Utah"), value: "UT"),
  DropdownMenuItem(child: Text("Vermont"), value: "VT"),
  DropdownMenuItem(child: Text("Virginia"), value: "VA"),
  DropdownMenuItem(child: Text("Washington"), value: "WA"),
  DropdownMenuItem(child: Text("West Virginia"), value: "WV"),
  DropdownMenuItem(child: Text("Wisconsin"), value: "WI"),
  DropdownMenuItem(child: Text("Wyoming"), value: "WY"),
];
